# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /backend

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /backend

_imagine:
    resource: .
    type:     imagine

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /