<?php

namespace Argidomin\AppBundle\Entity\Menus\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajesRepository extends EntityRepository
{
}