<?php

namespace Argidomin\AppBundle\Entity\Menus\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulosRepository extends EntityRepository
{

    public function getModulosInferiores()
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();

        return $query->select(['m'])
            ->from('AppBundle:Menus\Modulos', 'm')
            ->where($query->expr()->eq('m.posicion',':izquierda'))
            ->orWhere($query->expr()->eq('m.posicion',':derecha'))
            ->andWhere($query->expr()->eq('m.estado',':estado'))
            ->setParameters([':izquierda' => 'izquierdaInferior',
                             ':derecha'   => 'derechaInferior',
                             ':estado'    => true])

            ->getQuery()->getResult();
    }
}
