<?php

namespace Argidomin\AppBundle\Entity\Menus\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionesRepository extends EntityRepository
{
    public function getSeccion($ruta)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();
        return $query->select(['s'])
                        ->from('AppBundle:Menus\Secciones', 's')
                        ->where($query->expr()->eq('s.ruta',':ruta'))
                        ->andWhere($query->expr()->eq('s.estado',':estado'))
                        ->setParameters([':ruta'=> $ruta,
                                         ':estado' => true])
                        ->getQuery()->getOneOrNullResult();


    }

    public function getSeccionesMenu($menu)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();

        return $query->select(['s,m'])
                     ->from('AppBundle:Menus\Secciones', 's')
                     ->innerJoin('s.menu','m')
                     ->where($query->expr()->eq('m.slug',':menu'))
                     ->andWhere($query->expr()->eq('s.estado',':estado'))
                     ->setParameters([':menu'=> $menu,
                                      ':estado' => true])
                     ->orderBy('s.posicion', 'ASC')
                     ->getQuery()->getResult();
    }

    public function getSubsecciones($padre)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();

        return $query->select(['s','p'])
            ->from('AppBundle:Menus\Secciones', 's')
            ->innerJoin('s.seccionPadre','p')
            ->where($query->expr()->eq('p.slug',':padre'))
            ->andWhere($query->expr()->eq('s.estado',':estado'))
            ->orderBy('s.posicion', 'ASC')
            ->setParameters([':padre'=> $padre,
                             ':estado' => true])

            ->getQuery()->getResult();

    }
}
